spring:
  application:
    name : vaultbase-app
  datasource:
    url: jdbc:postgresql://localhost:5432/authserverdb
    username: ldamuleli
    password: Lodav72#
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

